### ISSUE TITLE
ColorShemes.jl colormap suggestions

### ISSUE THREAD

**Issue by briochemc** [tsipkens/cmap#5]
Just wanted to share a link to the [ColorSchemes.jl](https://juliagraphics.github.io/ColorSchemes.jl/stable/catalogue/#colorbrewer) catalogue (for Julia). Just thought you'd be interested in it as a potential resource because copying a colormap here would then only require a little copy-pasting.

**Comment by tsipkens** [comment]
This is a great resource. I have added a link to this resource in the README to record it more permanently in this repository.
